GreenTeaProgrammers/WhereChildBus

machine_learning/pyproject.toml
machine_learning/requirements-dev.lock
machine_learning/requirements.lock
machine_learning/src/face_detect_model/config.yaml
machine_learning/src/face_detect_model/model/model.py

- https://github.com/orgs/GreenTeaProgrammers/projects/2?pane=issue&itemId=52795495
- 画像処理用のCNNモデルの定義
- HPの最適化(学習時に最適化)
- なし
- なし
- 学習データ未定義のため無し
- Modelアーキテクチャは文献からCNNになりました．とりあえずそれっぽいパラメータを追加しています．

Feature/machine learning/model define

---

backend/domain/repository/ent/guardian.go
backend/domain/repository/ent/guardian/guardian.go
backend/domain/repository/ent/guardian/where.go
backend/domain/repository/ent/guardian_create.go
backend/domain/repository/ent/guardian_update.go
backend/domain/repository/ent/migrate/schema.go
backend/domain/repository/ent/mutation.go
backend/domain/repository/ent/nursery.go
backend/domain/repository/ent/nursery/nursery.go
backend/domain/repository/ent/nursery/where.go
backend/domain/repository/ent/nursery_create.go
backend/domain/repository/ent/nursery_update.go
backend/domain/repository/ent/runtime.go
backend/domain/repository/ent/schema/guardian.go
backend/domain/repository/ent/schema/nursery.go

refactor: schemaを変更

---

backend/usecases/guardian/guardian.go
backend/usecases/nursery/nursery.go
backend/usecases/utils/utils.go

なし
ハッシュとパスワードの比較を修正
なし
ログイン
なし
していない。
実装が間違ってるとかなりfatalなのでstrictにレビューして下さい

fix:ログイン時のパスワードの比較を修正

---

backend/domain/repository/ent/child.go
backend/domain/repository/ent/child/child.go
backend/domain/repository/ent/child/where.go
backend/domain/repository/ent/child_create.go
backend/domain/repository/ent/child_query.go
backend/domain/repository/ent/child_update.go
backend/domain/repository/ent/client.go
backend/domain/repository/ent/migrate/schema.go
backend/domain/repository/ent/mutation.go
backend/domain/repository/ent/nursery.go
backend/domain/repository/ent/nursery/nursery.go
backend/domain/repository/ent/nursery/where.go
backend/domain/repository/ent/nursery_create.go
backend/domain/repository/ent/nursery_query.go
backend/domain/repository/ent/nursery_update.go
backend/domain/repository/ent/schema/child.go
backend/domain/repository/ent/schema/guardian.go
backend/domain/repository/ent/schema/nursery.go

fix: ユニーク制約とエッジの修正

---

backend/usecases/child/child.go

fix: childのusecaseを修正

---

machine_learning/pyproject.toml
machine_learning/requirements-dev.lock
machine_learning/requirements.lock
machine_learning/src/face_detect_model/DetectFaceAndClip/detectFaceAndClip.py

- なし
- 顔検出とクリッピングに関するコードのリファクタリング
　- detectFaceUtil.pyのimportをプロジェクトの直下からのimportに変更
　- 一部logをf-stringに変更
　- 一部エラーハンドリングを追加
- なし
- なし
- なし
- [] 別途，gRPC server用のコードでsrcディレクトリからの実行ができることを確認しました
- レビュワーへの参考情報（実装上の懸念点や注意点などあれば記載）

refactor(ml): 顔検出とクリッピングに関するコードのリファクタリング

---

machine_learning/.gitignore
machine_learning/requirements-dev.lock
machine_learning/requirements.lock
machine_learning/src/face_detect_model/DetectFaceAndClip/detectFaceAndClip.py
machine_learning/src/face_detect_model/config.yaml
machine_learning/src/face_detect_model/data/faceDetectDataset.py
machine_learning/src/face_detect_model/main.py
machine_learning/src/face_detect_model/trainer.py
machine_learning/src/face_detect_model/util.py
machine_learning/src/proto-gen/machine_learning/v1/server.py

- https://github.com/orgs/GreenTeaProgrammers/projects/2?pane=issue&itemId=53534456
- https://github.com/orgs/GreenTeaProgrammers/projects/2/views/1?pane=issue&itemId=53534567
- GCSの画像を用いた学習の実装
- gRPCサーバーの学習用メソッドの定義
- CloudRunにデプロイし，正常に学習が行われることを確認
- 推論メソッドの実装
- リファクタリング
- 画像が登録されたタイミングで顔検出とクリップ処理が走る
- 何ができなくなるのか？（あれば。無いなら「無し」で OK）
- [] ローカル環境(M2 Macbook Air, Docker image)に建てられたgRPCサーバーにPostmanからリクエストを送ることにより動作を確認
- [] 本番環境(CloudRun)に建てられたgRPCサーバーにPostmanからリクエストを送ることにより動作を確認
- 
- レビュワーへの参考情報（実装上の懸念点や注意点などあれば記載）

Feature/machine learning/cloudrun for train

---

machine_learning/src/face_detect_model/DetectFaceAndClip/detectFaceAndClip.py
machine_learning/src/face_detect_model/DetectFaceAndClip/detectFaceUtil.py
machine_learning/src/face_detect_model/data/faceDetectDataset.py
machine_learning/src/face_detect_model/gcp_util.py
machine_learning/src/face_detect_model/main.py
machine_learning/src/face_detect_model/pred.py
machine_learning/src/face_detect_model/trainer.py
machine_learning/src/face_detect_model/util.py
machine_learning/src/proto-gen/machine_learning/v1/server.py

- なし
- machine-learningに関するファイル群のリファクタリング
- なし
- なし
- なし
- [] ローカル上と本番環境にて動作を確認
- レビュワーへの参考情報（実装上の懸念点や注意点などあれば記載）

refactor(ml)

---

.github/workflows/deploy_cloudrun_machine_learning.yml

- なし
- Github Actionsでのmachine-learningディレクトリ以下に対するCI/CDの構築
- なし
- なし
- なし
- なし

Feature/machine learning/cicd

---

machine_learning/Dockerfile

- なし
- Github Actionsでデプロイした際に発生するエラーへの対応
- なし
- なし
- なし
- [] なし
- なし

Feature/machine learning/cloudrun for pred

---

machine_learning/src/face_detect_model/pred.py
machine_learning/src/face_detect_model/util.py

- なし
- 笑顔判定の機能を追加
- 判定された画像をGCSに保存
- なし
- なし
- なし
- [] なし
- なし

feat(ml): 笑顔判定の機能を追加

---

frontend/where_child_bus_guardian/lib/app.dart
frontend/where_child_bus_guardian/lib/components/utils/custom_bottom_app_bar.dart
frontend/where_child_bus_guardian/lib/components/utils/wave_clipper.dart
frontend/where_child_bus_guardian/lib/pages/daily_page/components/has_item_state.dart

- なし
- BottomNavigationBarの背景色・アイコンの色の変更と波形の追加を行いました。
- なし
- なし
- なし
- BottomNavigationBarの高さが波形を追加した分、若干高くなっています。

feat:波形のBottomNavigationBarを追加

---

frontend/where_child_bus_guardian/lib/app.dart
frontend/where_child_bus_guardian/lib/components/utils/custom_app_bar.dart
frontend/where_child_bus_guardian/lib/components/utils/custom_bottom_app_bar.dart
frontend/where_child_bus_guardian/lib/components/utils/half_circle_painter.dart
frontend/where_child_bus_guardian/lib/components/utils/wave_clipper.dart
frontend/where_child_bus_guardian/lib/pages/daily_page/components/has_item_state.dart
frontend/where_child_bus_guardian/lib/pages/daily_page/daily_page.dart

-なし
- appBarの形と色をデフォルトから変更しました。
-なし
- なし
- なし
-なし

feat: appBarのデザインを追加

---

frontend/where_child_bus/lib/main.dart
frontend/where_child_bus/lib/pages/auth_page/auth_page.dart

- なし
- 保育園側アプリのタイトルを「ほいくるーず」に変更しました。
- なし
- なし
- なし
- なし

chore: 保育園側アプリのタイトルを修正しました

---

frontend/where_child_bus_guardian/lib/pages/auth_page/auth_page.dart
frontend/where_child_bus_guardian/lib/pages/check_page/check_page.dart
frontend/where_child_bus_guardian/pubspec.lock

- なし
- 乗車有無のチェックページに看板を追加しました。
- なし
- なし
- なし
- なし

feat:乗車有無のチェックページに看板を追加

---

frontend/where_child_bus_guardian/ios/Runner/Info.plist
frontend/where_child_bus_guardian/lib/pages/daily_page/components/daily_record_body.dart
frontend/where_child_bus_guardian/lib/pages/daily_page/components/daily_record_slider.dart

- 無し
- 表情のアイコンの追加とアクセス権限を追加しました。
- なし
- なし
- なし
-Androidエミュレータで動作確認済み
- なし

feat: 表情アイコンの追加とアクセス権限の追加

---

frontend/where_child_bus_guardian/lib/components/utils/current_time_body.dart
frontend/where_child_bus_guardian/lib/pages/daily_page/components/daily_record_slider.dart

- 無し
- オーバーフローを修正しました
- なし
- 無し
- 無し
- なし

fix: オーバーフローを修正

---

frontend/where_child_bus_guardian/lib/pages/map_page/map_page.dart

- なし
-  busTypeを現在時刻をもとに更新するよう修正しました
-なし
-なし
- なし
- なし

fix: busTypeを現在時刻をもとに更新するよう修正

---

frontend/where_child_bus/lib/pages/student_list_page/components/utils/input_form_body.dart

園児作成ページで保護者とバスが最新の状態にならないバグを修正

fix:園児作成ページで毎回保護者とバスをフェッチするように修正

---

frontend/where_child_bus/lib/pages/bus_list_page/bus_edit_page/bus_edit_page.dart

バス名の長さのバリデーションが常にfalseになる問題を修正

fix:バス名の長さのバリデーションを修正

---

frontend/where_child_bus_guardian/lib/pages/map_page/map_page.dart

feat:mapページにrefreshIndicatorを実装
